### ISSUE TITLE
Problème avec les fichiers "getValue.php"

### ISSUE THREAD

**Issue by LordySalty** [Nerfez/LiveChatTwitch#10]
Salut, tout d'abord merci pour le partage de ton travail pour le coup tu gères, j'ai réaliser tout les étapes de la réalisation du projet sans trop de problème mais je ne comprend pas comment modifier correctement les fichier "getValue.php" fournis ayant réaliser que trés peu de php et encore moins de projet de se type.

Je me suis retrouver avec un fichier comme ceci : 
```
<?php
$bdd = new PDO('mysql:host=mysql-lordysalt.alwaysdata.net;dbname=lordysalt_livechat', "lordysalt", "); //A remplacer par vos valeurs

$sql = "SELECT * FROM image"; //votre requête, ici on va lire toutes nos valeurs

$stmt = $bdd->query($sql)->fetchAll();

foreach($stmt as $row){
    echo $row['ImageTime']."$".$row['Width']."$".$row['Height']."$".$row['url']."$".$row['ImageTexte'];
}//pareil vos Colonnes doivent correspondre aux noms dans votre Table
?>
```
Je crois que le problème vient de la ligne 2 mais je n'en suis pas sur.

En effectuant un test complet du bot , se qu'il se passent est que le bot reçois belle est bien la commande mais le fichier ( image ou vidéo ) n'est pas transmit aux fichiers "index.html" et donc les média choisi ne se modifie pas. 

Merci d'avance

**Comment by Nerfez** [comment]
Salut ! Est-ce que je pourrai voir à quoi ressemble ta table "image" dans ta base de donnée s'il te plaît et, également, est-ce que en envoyant une image depuis le channel discord cela update bien les valeurs dans la base de donnée ?

**Comment by LordySalty** [comment]
ma table image ressemble à ceci :
![image](https://github.com/Nerfez/LiveChatTwitch/assets/140567302/9ba3116b-ad61-4d92-a40d-e1f3ee42e3a0)

de plus rien ne semble changer dans la base de donnée lorsque je fait une commande depuis le chanel discord .

**Comment by LordySalty** [comment]
j'ai également cette erreur après le débug de "index.js" 
 ![image](https://github.com/Nerfez/LiveChatTwitch/assets/140567302/7c56c79d-0e87-4ab5-ac2e-84f05780b756)

**Comment by Nerfez** [comment]
Si la base de donnée se met bien à jour alors c'est que le problème vient des fichiers `getValue.php`. Vérifie bien que les valeurs de connexion à la bdd correspondent à ton fichier `index.js`. Dans ton cas ça doit ressembler à ça : (en mettant ton mot de passe de connexion à la bdd)

Index.js :
![livechatLordy1](https://github.com/Nerfez/LiveChatTwitch/assets/87040538/e8552276-bf0e-4738-ade0-675a09ed089b)

getValue.php :
![livechatLordy2](https://github.com/Nerfez/LiveChatTwitch/assets/87040538/bdf440f2-af45-4b98-b885-50df6a32c036)

Le message en bleu qui s'affiche, on a pas à s'en préoccuper ça ne fait pas planter l'application

**Comment by ayrtonbardiot** [comment]
@LordySalty Salut, pense à cacher tes infos de connexions au serveur : hôte, nom d'utilisateur ;)

**Comment by LordySalty** [comment]
@ayrtonbardiot  Pas d'inquiétude j'ai modifier les info sensible , de plus j'ai la parenthèse que tu mention et juste présente sur la capture car justement j'ai enlevé mon réel mot de passe et j'ai par extension supprimé une parenthèse en plus XD

@Nerfez , Après vérification il me semble que mon code est exactement comme celui que tu ma montrés ,  je pense qu'il est possible que le tout marche mais que je ne sache pas l'url exacte , quand tu parle des url "https://*****index.php" et "https://*****/Video/index.php" , par quoi remplace tu les "*****" ?

**Comment by LordySalty** [comment]
C'est fort possible seulement je ne comprend/sait pas comment faire ...

**Comment by Nerfez** [comment]
Il y a quelques personnes qui m'ont demandé de faire une sorte de tuto pour tout configurer donc je vais essayer de sortir une vidéo dessus ce week end sinon si tu veux essayer par toi même, rends toi sur alwaysdata dans l'onglet ftp :
![image](https://github.com/Nerfez/LiveChatTwitch/assets/87040538/90ef7491-3683-4d8a-995e-dd98d89ccc6f)

Sur cet interface tu récupèreras le hote FTP / user / password, grâce à ces 3 valeurs on peut se connecter avec un client ftp comme [Filezilla](https://filezilla-project.org/download.php?platform=win64https://filezilla-project.org/download.php?platform=win64) par exemple. Une fois connecté tu y déposes tes fichiers dans le dossier `www` comme suit :
![image](https://github.com/Nerfez/LiveChatTwitch/assets/87040538/8b9b3de5-9b0d-44d0-9890-931eddb0b15b)

**Comment by LordySalty** [comment]
En cherchant un peu j'ai pu faire tout cela , la page pour les image marche super bien , pour les vidéo par contre le site ne s'actualise pas je vais cherchez un peu et faire un update quand j'aurais trouver qlq chose

**Comment by LordySalty** [comment]
Petit update juste pour une petit question , quand j'utiliser la commande vidéo , la vidéo n'a pas de son sur le live , est ce que c'est normal ou y à t'il un moyen d'arranger cela ?

**Comment by Nerfez** [comment]
ça peut arriver que l'audio plante mais si ça le fait sur toutes les vidéos c'est pas normal mais dans l'immédiat j'ai pas de solution

**Comment by LordySalty** [comment]
Je suis justement sur OBS mais je vais regarder sa merci
