### ISSUE TITLE
Probleme site Always Data, et code VSC 

### ISSUE THREAD

**Issue by SticksOnTheBeach** [Nerfez/LiveChatTwitch#11]
Bonjour, je voulais savoir pour plusieurs chose, notamment ce qu'il fallait mettre dans toutes les cases comme celle-ci ( car j'avais fait en localhost pour la base de données, c'est à dire que la base de données était hébergée sur mon pc ) :

![Screenshot_1](https://github.com/Nerfez/LiveChatTwitch/assets/142520621/47dade99-b8e7-4629-8075-81dfabfce399)
"
    host: ' ',
    port: ' ',
    user: ' ',
    password: ' ',
    database: ' ',
    charset:
"
et je voulais notamment savoir pour le site Always Data comment je fait pour faire 1 seul site qui contient comme fichier racine "image" et "vidéo" car sur mon site je n'ai que des vidéos et d'ailleurs au bout d'un certains temps le site crash, c'est à dire que il me met une vidéo qui y était de base et après quelques secondes le site crash 

![Capture d'écran 2023-08-17 172636](https://github.com/Nerfez/LiveChatTwitch/assets/142520621/5559d94a-89fa-47b9-b0c6-129cfd0b2a36)

![Capture d'écran 2023-08-17 172643](https://github.com/Nerfez/LiveChatTwitch/assets/142520621/95df8d51-a08d-4a48-b8af-a9698632dde6)

**Comment by SticksOnTheBeach** [comment]
et j'ai aussi un probleme avec mon bot discord ducoup quand j'ecris un message dans le channel avec le prefix et tt, et bien il devrait me renvoyer comme message Connexion a la BDD ore il ne me l'envoie pas, donc je ne comprend pas.
![image](https://github.com/Nerfez/LiveChatTwitch/assets/142520621/39b3b746-79a5-4e6a-b70c-deccb491a34f)
![image](https://github.com/Nerfez/LiveChatTwitch/assets/142520621/0aed4995-4430-44df-bd3a-68b4eee4f257)

**Comment by SticksOnTheBeach** [comment]
Slt, merci de ta réponse je vais essayer tout ça, par contre tu les as upload où t'es fichiers car ça me met qu'il ont été déposé le mois dernier ?

**Comment by SticksOnTheBeach** [comment]
> Salut @SticksOnTheBeach je suis désolé de répondre que mtn j'suis bcp occupé par mon travail ces derniers temps, pour ta première question regarde bien [les commentaires du fichier index.js](https://github.com/Nerfez/LiveChatTwitch/blob/main/Discord/index.js) j'ai laissé des exemples. Concernant ta deuxième interrogation jette un coup d'oeil à la discussion #10 tu trouveras peut être ta réponse sur les fichiers à upload et enfin j'avais update pas mal de fichier quelques jours après ton message donc ton dernier soucis à du être corrigé. Si tu as besoin de plus de détails dis moi j'essaierai d'être plus réactif

bon finalement j'ai trouvé le petit soucis que j'ai c'est que dans mon FTP je n'ai pas de fichier nommé www

**Comment by Nerfez** [comment]
pour l'image, j'ai fais une commande `!fullscreen` qui permet de définir soit les dimensions de l'image soit par défaut 1920 x 1080, pour la vidéo le changement est bien effectué en base de donnée ?

**Comment by SticksOnTheBeach** [comment]
Merci de ta réponse, je vais essayer tout de suite, et pour la vidéo comment ça "le changement a bien été effectué", car j'ai tout bien fait normalement

**Comment by Nerfez** [comment]
En faite c'est pour déterminer d'où vient le problème car en envoyant une vidéo, les nouvelles valeurs sont stockées dans la base de donnée et donc si l'affichage n'est pas actualisé alors le problème vient de la requête / page html mais si les valeurs ne sont même pas parvenu à être inscrites dans notre base de donnée alors le soucis viens du fichier `index.js`

**Comment by SticksOnTheBeach** [comment]
ok je vais te dire ça, je t'envoie ça

**Comment by SticksOnTheBeach** [comment]
Où est ce que c'est marqué sur la bdd

**Comment by Nerfez** [comment]
![image](https://github.com/Nerfez/LiveChatTwitch/assets/87040538/995f2c50-4625-4a2b-9959-55e5145d9430)
Quand tu cliques sur le nom de ta table, dans le premier onglet où tu arrives (browse) regarde si les données correspondent avec celles que tu viens d'envoyer

**Comment by SticksOnTheBeach** [comment]
![image](https://github.com/Nerfez/LiveChatTwitch/assets/142520621/c01c12c2-c058-44d8-877a-928bb9047c57)
![image](https://github.com/Nerfez/LiveChatTwitch/assets/142520621/78a7a245-7d9f-485c-9844-020cb718336f)
oui, les valeurs sont les mêmes, mais elle ne s'affiche pas

**Comment by Nerfez** [comment]
Et dans ton fichier `getValue.php` de ton dossier video, tu as le bon nom de serveur/ nom de base donnée etc ? ça peut arriver qu'il y est une faute de frappe

**Comment by Nerfez** [comment]
C'est bizarre parce que tu as les bons noms de colonnes aussi, je viens de refaire un test j'ai 0 soucis avec l'affichage vidéo donc si ton fichier `ndex.html` est à jour et que `getValue.php` a aucune erreur alors j'vois pas trop comment régler ça dans l'immédiat

**Comment by SticksOnTheBeach** [comment]
Bah, j'ai tout mis à jour, donc moi non plus je ne sais pas trop pourquoi ça fait ça, je pense juste que tout fonctionne correctement car la video est présente, mais ont ne l'as voit juste pas

**Comment by SticksOnTheBeach** [comment]
mais merci qd meme je regarderai ça à un autre moment et je te redirais si cela fonctionne

**Comment by Nerfez** [comment]
Ouai je suis désolé de pas pouvoir faire plus je continuerai de chercher une solution

**Comment by SticksOnTheBeach** [comment]
Slt, je te renvoie un message pour te demander si c'est normal que lorsque j'envoie une image, l'image s'affiche comme ça ( en sachant que je n'est pas activé le fullscreen et que si je l'active ça ne change rien ):
![image](https://github.com/Nerfez/LiveChatTwitch/assets/142520621/cf606246-a2d1-4c52-b0d7-c7e31e8a4482)

**Comment by Nerfez** [comment]
![image](https://github.com/Nerfez/LiveChatTwitch/assets/87040538/9e45a358-51b4-4494-aef8-3cdebc123241)
Ta source navigateur doit faire l'intégralité de ton écran streamlabs et réglé sur 1920x1080 (j'ai mis à jour les 2 fichiers `style.css` pour que l'image / vidéo apparaisse en haut à droite et que le texte s'affiche en bas)

**Comment by SticksOnTheBeach** [comment]
Ok merci je vais essayer tout ça mais j'ai une autre question ( dsl de deranger ) mais pourquoi toi tu as sur Streamlabs, une source pour img et unee autre pour video ? j'aimerais savoir stp

**Comment by Nerfez** [comment]
Une source qui à pour url le site vidéo pour toi ça devrait être `http://user.alwaysdata.net/video/index.html`  avec le `user` remplacé par ton nom biensûr et une autre source pour les images `http://user.alwaysdata.net/index.html`

**Comment by SticksOnTheBeach** [comment]
ah mais moi je mettait tout sur une source c'est pour ça que les vidéos ne fonctionnait pas

**Comment by SticksOnTheBeach** [comment]
Ptn mais mec, je suis trop con, merci de me sauver, je n'y avais pas pensée enfaites cbon dcp

**Comment by Nerfez** [comment]
mdrr tranquille si tout fonctionne c'est le principal

**Comment by Nerfez** [comment]
mmh j'vois pas ce que tu veux dire, c'est genre comment faire pour que ça s'affiche par dessus un jeu ? Normalement si tu places tes sources navigateurs au dessus de ta source de jeu ça devrait suffire en tout cas j'ai pas cocher ça

**Comment by Nerfez** [comment]
et si tu parles de placer plusieurs vidéos / images qui se superposent c'est pas possible dans l'état actuel

**Comment by SticksOnTheBeach** [comment]
c'est a dire que si une personnes ou moi met une video / image je ne l'as verrais pas sur mon écran ?

**Comment by Nerfez** [comment]
ça s'affichera sur le stream et toi tu pourras le voir directement sur streamlabs mais oui ça n'apparaitra pas sur ton écran de jeu (je sais pas si c'est assez clair)

**Comment by SticksOnTheBeach** [comment]
D'accord, c'est que ce n'est pas possible ou bien tu ne sais pas comment le faire, car je pense que c'est possible, et j'ai déjà entendu des gens et vu des gens ou l'image était répercuté sur leur écran, ( ça n'avais aucun rapport avec le live chat de la ccb mais c'etait pour un autre truc et j'avais deja vu un plugins du genre )

**Comment by Nerfez** [comment]
là comme ça je ne pourrai pas le faire mais il faut que je me renseigne si jamais t'as déjà des pistes de vidéos ou documentation que je peux feuilleter j'suis chaud

**Comment by SticksOnTheBeach** [comment]
bah vzy, j'essayerais de trouver ça, je vais également essayer de coder ça à partir de chose déjà existante, mais je vais voir si il n'y as pas un genre de logiciel ou je pourrais ramener l'image envoyer sur ce logiciel et le logiciel serais juste par dessus ton jeux, et il mettrais l'image ou la vidéo

**Comment by Nerfez** [comment]
@SticksOnTheBeach  regarde [cette application](https://github.com/lmachens/skeleton) ça devrait t'intéresser, tu télécharges et dé-zip, tu lances le fichier `skeleton.exe` et tu peux y ajouter le lien du site avec les dimensions de ton écran j'ai pas testé en jouant à un jeu mais en restant juste sur le bureau ça marche nickel et je pense que tu cherches un truc comme ça

**Comment by SticksOnTheBeach** [comment]
Merci bcp, je vais tester ça, jte redis si ça fonctionne en jeu.

**Comment by SticksOnTheBeach** [comment]
Et si, pour faire pop l'image / vidéo, sur notre écran, il faudrait faire un genre de logiciel "Iframe" qui lorsqu'une requête est envoyée du site au logiciel, cela ouvre "l'Iframe" qui fait apparaître une fenêtre où l'image / la vidéo est sur l'écran.
