### ISSUE TITLE
Soucis sur les vidéos

### ISSUE THREAD

**Issue by bibilbeot** [Nerfez/LiveChatTwitch#16]
Bonjour,

J'ai des soucis sur le livechat quand je met une vidéo il arrive que des fois on a 1 sec du son de la vidéo puis plus rien.

Possible d'avoir une piste ?

Merci

**Comment by Nerfez** [comment]
Bonjour, essayez de séparer la piste audio et veillez bien à n'avoir que streamlabs d'ouvert et non le site en plus sur un onglet ça peut provoquer des problèmes
![image](https://github.com/Nerfez/LiveChatTwitch/assets/87040538/45d44daa-ad3b-4a4f-8445-31c5256b1842)
![image](https://github.com/Nerfez/LiveChatTwitch/assets/87040538/75222875-2eab-4d04-84d4-aece56e4db3f)

**Comment by bibilbeot** [comment]
enfaite soit on entend au début mais pas a la fois

> Bonjour , On viens de testé avec un ami actuellement cette solution sur obs classique (non streamlabs obs je pense pas que ça causerai soucis) des fois l'un entend la vidéo et pas l'autre et des fois c'est l'inverse

enfaite soit on entend au début puis plus rien soit au début il y a rien puis on a tout l'audio de la vidéo

**Comment by Nerfez** [comment]
![image](https://github.com/Nerfez/LiveChatTwitch/assets/87040538/35374321-2319-4d91-9c68-457cdf94c3fe)
Je pense que le problème venait de la ligne 80 du fichier `index.html` dans le dossier video, j'ai testé avec 4/5 vidéos aux formats .MP4 et .mov aucun problèmes, dites moi de votre côté

**Comment by bibilbeot** [comment]
tout est bon de mon coté aussi 

je te remercie !
