### ISSUE TITLE
Problème partie web

### ISSUE THREAD

**Issue by StripesEU** [Nerfez/LiveChatTwitch#18]
Salut, gg pour le bot  c'est cool. 

J'ai un petit soucis sur la partie lien web. 

Peux tu me dire si les fichiers du dossier livechat tu les glisses directement à la racine du site ou bien tu créer un dossier Livechat et on y glisse les fichiers ? car j'ai aucune autre erreur, le bot se connecte à ma bdd mais j'ai rien qui apparait quand je fais la commande.

**Comment by Nerfez** [comment]
![image](https://github.com/Nerfez/LiveChatTwitch/assets/87040538/1c05a04d-0037-4a39-8773-2079643eb15a)
C'est toi qui décides, perso j'ai un sous dossier LiveChat car j'héberge une autre page à la racine mais tu peux très bien les mettre à la racine (dossier www)

**Comment by Nerfez** [comment]
![image](https://github.com/Nerfez/LiveChatTwitch/assets/87040538/b46eab8f-7a69-44a8-a0f1-b11627ce813f)
oui, une source navigateur avec le lien et la résolution 1920 x 1080, c'est également important de cocher "controller l'audio" et de choisir le volume adéquat en bas à droite

**Comment by StripesEU** [comment]
![image](https://github.com/Nerfez/LiveChatTwitch/assets/156974577/29d4191c-06bc-4345-bb5f-fcf291d48d9a)

j'ai bien comme toi mais rien ne se passe

**Comment by Nerfez** [comment]
Les données sont bien alimentées en bdd ? Et est ce que tu utilises les derniers fichiers à jour, j'ai fais pas mal de changement hier

**Comment by StripesEU** [comment]
les données sont bien enregistrées dans la Bdd 
![image](https://github.com/Nerfez/LiveChatTwitch/assets/156974577/aa6f9281-a1a6-4f43-bc8d-8d51d41ea6b2)

et je l'ai setup hier avec le fichier à jour donc

**Comment by Nerfez** [comment]
normalement la page est sensé supprimé automatiquement la liste au fur et à mesure, vide toutes les données de la table et essaie d'envoyer à nouveau une image ou vidéo

**Comment by Nerfez** [comment]
![image](https://github.com/Nerfez/LiveChatTwitch/assets/87040538/ae4cc091-d324-4275-9d78-056f8cc452f3)
Ok je pense avoir trouvé le soucis, remplace la ligne 36 par celle-ci dans le fichier `index.html`

**Comment by StripesEU** [comment]
je peux plus start le bot 

![image](https://github.com/Nerfez/LiveChatTwitch/assets/156974577/428f3ff7-32bf-490a-afca-5fc86fd7aa29)

**Comment by Nerfez** [comment]
tu n'as pas fais la commande `npm i` ? sinon installe le directement : `npm install discord.js`

**Comment by StripesEU** [comment]
je l'avais déjà installé mais là y'a une autre erreur 
![image](https://github.com/Nerfez/LiveChatTwitch/assets/156974577/0eb53be7-14a8-468b-858d-6160a2053a8e)

**Comment by Nerfez** [comment]
non ca veut dire que tu n'as pas fais la commande npm i là il te demande d'installer mysql, soit `npm install mysql`

**Comment by StripesEU** [comment]
j'ai la modif du index.html ça change rien et la bdd ne se vide pas au fur et à mesure

**Comment by StripesEU** [comment]
mb ça fonctionne
