### ISSUE TITLE
[Dernière Build] Text only value 'createdTime' = 00 / Pas d'affichage

### ISSUE THREAD

**Issue by GiZcesi** [Nerfez/LiveChatTwitch#20]
Hello,

J'ai pu effectuer le setup comme convenu, rien de spécial.
Les creds mysql sont bien configurés (php et js), les requetes apparaissent bien dans la DB.
Mais 0 affichage sur la page index.html. 

![image](https://github.com/Nerfez/LiveChatTwitch/assets/121864537/90f5e374-7573-496d-81a0-e2909e56a686)

Help.

**Comment by GiZcesi** [comment]
Update j'ai fix le temps dans l'index.JS, le text only affiche maintenant correctement l'heure.

`  texte = checkTexte(texte);
  console.log("affichage de :", time, texte, avatar, username);
  createdTime = new Date();
  con.query(
    `INSERT INTO data (url, Time, Texte, Width, Height, Audio, username, avatar, CreatedTime) VALUES ('','${time}','${texte}','','','','${username}','${avatar}', '${createdTime}')`
  );
}`

TO

`  texte = checkTexte(texte);
  console.log("affichage de :", time, texte, avatar, username);
  createdTime = new Date();
  const formattedCreatedTime = createdTime.toISOString().slice(0, 19).replace('T', ' ');
  con.query(
    `INSERT INTO data (url, Time, Texte, Width, Height, Audio, username, avatar, CreatedTime) VALUES ('','${time}','${texte}','','','','${username}','${avatar}', '${formattedCreatedTime}')`
  );
}`

**Comment by GiZcesi** [comment]
Par contre toujours meme blem, la ligne se delete pas dans la base SQL et ne s'affiche pas donc bloque la queue

**Comment by GiZcesi** [comment]
![image](https://github.com/Nerfez/LiveChatTwitch/assets/121864537/7dc90512-5388-434a-b97d-d5aa46bc7c03)

**Comment by GiZcesi** [comment]
OK jai fix yavais un return sur le ajax ici :
![image](https://github.com/Nerfez/LiveChatTwitch/assets/121864537/8811f1e7-1c1e-43a7-a5af-ca1f64db1ffa)

**Comment by GiZcesi** [comment]
Ducoup j'ai juste remis **_"updateUI(messageRecu);"_** a la place et ca marche :)

**Comment by GiZcesi** [comment]
Update, l'heure n'était pas necassaire sur la DB donc pas important de modifier dans le index.js, et changer le return casse tout le ajax.onload :(

Retour au point de départ, Image & Video OK par contre texte NOK

**Comment by Nerfez** [comment]
Effectivement, je te remercie pour ton intérêt je prends en cours de route mais il semble bien il y avoir un soucis pour le texte je regarde ca 👍

**Comment by Nerfez** [comment]
Alors j'ai merge les changements mais je vais énumérer pour comprendre mon raisonnement et les problèmes; 

#### Problèmes : 

- CreatedTime **pas** au bon **format** dans la bdd
- Only texte ne **s'affiche pas**
- Le delete ne fonctionne pas correctement (ne supprime pas le **livechat** en cours)

### Résolution :

#### Sur le fichier `index.js` :
- Dans le `handleTextOnlyMessage` on passe en paramètre de **url** l'image vide.png
![image](https://github.com/Nerfez/LiveChatTwitch/assets/87040538/c09fe3e7-002d-4ebd-adc5-6f61d822526e)

- Création d'une méthode pour **formatter** correctement : 
![image](https://github.com/Nerfez/LiveChatTwitch/assets/87040538/6b4369d0-f39f-4f98-a3af-30ec3f30b1f2)

On remplace alors les anciennement `formattedCreateTime` par directement `createdTime`, chaque createdTime est affecté directement avec la méthode.

![image](https://github.com/Nerfez/LiveChatTwitch/assets/87040538/33806353-d0db-4db9-90e6-e1ab2e4b8619)

#### Sur le fichier `deleteValue.php`

- On remplace la requete sql pour plus de précision
![image](https://github.com/Nerfez/LiveChatTwitch/assets/87040538/57800974-6563-4925-8f34-73e755f0402b)

#### Sur le fichier `index.html`

- On ajoute dans la condition de laisser passer si only texte
![image](https://github.com/Nerfez/LiveChatTwitch/assets/87040538/c5a60fdc-de4d-4b8f-94b4-d4042d559bfc)


Pour une compréhension peut être plus visuelle avec tous les commits voici en vert ce qui est rajouté et en rouge enlevé, directement visible [ici](https://github.com/Nerfez/LiveChatTwitch/commit/7330be65fe662a98d97238c9786ac965e5bef03a)

**Comment by GiZcesi** [comment]
Wow okay, c'était fast. 
Pour le coup j'ai tester sur la prod voici ce que j'ai pu constater :

- Le temps est bien fixé sur les requetes 
- Le texte only est bien fonctionnel 

Par contre :

- Aucune requete ne semble de supprimer a présent, elle loop a l'infini en restant dans la table. (creds bien changé sur la requete PHP)

**Comment by GiZcesi** [comment]
Ok houston, ca marche au top j'ai trouvé le problème. @Nerfez 

Dans ton deleteValue.php il ya un '$' en trop :)

![image](https://github.com/Nerfez/LiveChatTwitch/assets/121864537/bf161282-2a3f-4e73-9497-5337d0301585)

**Comment by GiZcesi** [comment]
Dernier problème les requetes audio ne se delete pas, c'etait deja present dans la build du mois dernier.
**Et je pense que tout sera fonctionnel si on arrive a fix ca. 👏**

**Comment by Nerfez** [comment]
Je pense qu'il doit manquer un 
```
setTimeout(() => {
          clearUI();
        }, time);   //avec time passé en paramètre
```

au sein de la fonction **updateAudio** dans `index.html` mais je ne pourrai faire les tests que ce soir quand je rentre du travail,
je fix ça tout à l'heure 👍

**Comment by GiZcesi** [comment]
Re, Oui c'est ce que jai fais apres avoir marquer mon dernier message !

Tout marche c'est nickel 🥳

![image](https://github.com/Nerfez/LiveChatTwitch/assets/121864537/54a25f4f-d69a-4daa-be72-06f8c776e4cc)

Faudrait commit avec ces changements :

- delete le $ avant le "$sql" en trop dans le `deleteValue.php`
- Add le timeout pour la fonction "updateAudio" dans `index.html`
