### ISSUE TITLE
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by Super-YuriYT** [Nerfez/LiveChatTwitch#3]
Bonjour, j'ai essayer votre code mais j'obtient a chaque fois la meme erreur

"Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'length')"
cette erreur est liée a la ligne 32
merci de pouvoir trouver une solution

Bonne continuation.

**Comment by Nerfez** [comment]
Bonjour, je ne pourrai effectuer de tests qu'à partir de ce soir mais je présume que cela vient du fichier "index.js" du bot discord. A quoi ressemble la commande que vous envoyée sur discord ? Est-ce qu'elle correspond bien aux formats suivants :
![formatCommande](https://github.com/Nerfez/LiveChatTwitch/assets/87040538/8cf5ed24-776d-41b3-8a76-bc80c29d9cbd)

**Comment by Nerfez** [comment]
Le fichier "index.js" à été mis à jour le problème venait bien, je pense, d'une mauvaise commande. Je vais ajouter une section dans le read me pour détailler comment exécuter une commande.
