### ISSUE TITLE
Uncaught Error Error: ER_BAD_FIELD_ERROR: Unknown column 'url' in 'field list'

### ISSUE THREAD

**Issue by Yuriassd** [Nerfez/LiveChatTwitch#6]
bonjour, j'ai essayer votre code et quand je le fais avec une image, l'image est "envoyer" mais elle s'affiche pas sur obs/streamlabs et quand je réessaye avec une seconde image, l'image ne s'envoie pas et sa me met une erreur bleu 
Error: Cannot enqueue Handshake after already enqueuing a Handshake.
![image_2023-07-12_165016888](https://github.com/Nerfez/LiveChatTwitch/assets/139366835/a15b885d-2ed8-4ed5-a7d9-f24aeb2422c3)

mais aussi quand j'essaye avec une video, elle est aussi dites "envoyer" mais elle s'affiche pas sur obs/streamlabs mais je recoit l'erreur rouge
Uncaught Error Error: ER_BAD_FIELD_ERROR: Unknown column 'url' in 'field list'
![image_2023-07-12_165313827](https://github.com/Nerfez/LiveChatTwitch/assets/139366835/c9e47359-0df6-4729-9198-1e4adf3d4e13)

Merci de votre aide

**Comment by Nerfez** [comment]
L'erreur "Cannot enqueue Handshake..." ne fait pas planter l'application, si l'url, timer et texte de l'image ne s'update pas dans la base de donnée, c'est un problème de réseau (proxy / VPN) qui bloque l'update. Pour la 2e erreur c'est parce que "url" n'existe pas dans la base de donnée. Si c'est la même que la mienne ou que le fichier "bdd.sql", il faut remplacer "url" par "VideoURL".
